### ISSUE TITLE
Bug in select_future

### ISSUE THREAD

**Issue by mo-kli** [MCZhi/DIPP#11]
There might be a bug in `select_future` https://github.com/MCZhi/DIPP/blob/main/utils/train_utils.py#L68.
This function uses the global variable `best_mode`, which is computed earlier in `MFMA_loss` using the ground truth. However, `select_future` is also used by the planner to select `plan_init` and the predicition mode considered during planning. This looks like cheating, instead `scores` or the reference path should be used in my opinion by `select_future`.

**Comment by MCZhi** [comment]
Thank you for your comment. Actually, this is intentional because in training we can access the ground truth and we assume the scorer gives the correct mode closest to the ground truth, but in testing we take the best mode from the trained scorer instead of "cheating". However, your comment is undoubtedly reasonable and you can modify the code to your idea.
