### ISSUE TITLE
Coordinates used in the bicycle model

### ISSUE THREAD

**Issue by jchengai** [MCZhi/DIPP#2]
Thanks for open sourcing your work! I have a question about the coordinates used in the bicycle model.

It looks like the center of the vehicle is used as the input coordinate, while the bicycle model assumes that coordinate to be located at the rear axle of the vehicle. This mismatch seems unreasonable to me. Have you noticed this problem and does this harm the performance of the model?  Please correct me if I missed any.

**Comment by MCZhi** [comment]
Thank you for being interested in our work. I admit there is a mismatch between the coordinates as you have pointed out. This is because the nonlinear optimizer becomes very unstable when we use the bicycle model (maybe due to its complexity), and I find that locating the coordinate on the rear axle could stabilize the optimizer and does not harm the planning performance. I would recommend using the unicycle model (physical model) if you think the rear-axle bicycle model is unsuitable.

**Comment by jchengai** [comment]
Thanks for your answer.
