### ISSUE TITLE
Pretrained model inquiry

### ISSUE THREAD

**Issue by Rex-sys-hk** [MCZhi/DIPP#22]
Thanks for the open source and your great work, Could you please offer the checkpoint used to get the closed-loop results in your paper? We ran your code getting a similar open loop test result but failed to get the same result in the closed loop test.

**Comment by MCZhi** [comment]
Hi @Rex-sys-hk, thank you for your interest in our work and for using our code. Unfortunately, due to the policy of the Waymo Dataset, we are not able to publish the trained model or checkpoints. However, we are more than happy to help you with any specific questions or issues you may have regarding the closed-loop test.

**Comment by Rex-sys-hk** [comment]
Sorry for just knowing the policy. Then, as you announced in the article, a subset of 100 data was used for the closed-loop test. Could you please offer the close-loop test data list?

**Comment by MCZhi** [comment]
Please refer to #4.

**Comment by Rex-sys-hk** [comment]
Many thanks!
